language: go
go:
  - master
sudo: required
install: go get -v github.com/spf13/hugo
before_script:
  - sudo pip install awscli
script:
  - cd src
  - hugo
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "hoangpaul.com"
  skip_cleanup: true
  region: "ap-southeast-2"
  upload-dir: src/public
after_deploy: |
  aws configure set preview.cloudfront true && \
  aws cloudfront create-invalidation --distribution-id "$AWS_CLOUDFRONT_ID" --paths "/index.html /*"
notifications:
    email:
        on_failure: always


