language: go
go:
  - master
sudo: required
install: go get -v github.com/gohugoio/hugo
before_script:
  - sudo pip install awscli
script:
  - cd "$TRAVIS_BUILD_DIR/src"
  - hugo
before_deploy:
  - cd "$TRAVIS_BUILD_DIR/src/public"
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "hoangpaul.com"
  skip_cleanup: true
  region: "ap-southeast-2"
after_deploy: |
  aws configure set preview.cloudfront true && \
  aws cloudfront create-invalidation --distribution-id "$AWS_CLOUDFRONT_ID" --paths "/index.html" "/*"
notifications:
    email:
        on_failure: always


