language: go
dist: xenial
go:
  - "1.12.5"
sudo: required
install:
  - pip install awscli
  - snap install hugo
script:
  - cd "$TRAVIS_BUILD_DIR/src"
  - hugo
before_deploy:
  - cd "$TRAVIS_BUILD_DIR/src/public"
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "hoangpaul.com"
  skip_cleanup: true
  region: "ap-southeast-2"
after_deploy: |
  aws configure set preview.cloudfront true && \
  aws cloudfront create-invalidation --distribution-id "$AWS_CLOUDFRONT_ID" --paths "/index.html" "/*"
notifications:
    email:
        on_failure: always


