languageCode = "en-au"
title = "Paul Hoang's website"
baseurl = "https://hoangpaul.com"
uglyurls = true

[params]
  GithubID = "HoangPaul"
  Name = "Paul Hoang"
  HeaderUsername = "Paul Hoang"
  Email = "paulkhoahoang@gmail.com"
  GoogleAnalytics = "UA-61022988-1"
  Greetings = "Welcome"
  About = "I put my projects here. Look around."

[menu]
  [[menu.header]]
    name = "projects"
    weight = 1
    url = "/projects.html"
  [[menu.header]]
    name = "contact"
    weight = 0
    url = "/contact.html"
